# http://docs.gitlab.com/ce/ci/yaml/README.html

image: node:12

variables:
  CI: "true"
  NODE_ENV: "test"

cache:
  paths:
    - node_modules/

before_script:
  - npm install --unsafe-perm

stages:
  - test
  - build
  - myTest

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build

myTest:
  stage: myTest
  script:
    - npm run lint